module.exports = [
    { text: '首页', link: '/' },
    { text: '个人网站', link: 'https://www.eveningwater.com' },
    // { text: 'ewColorPicker', link: 'https://eveningwater.github.io/ew-color-picker/' },
    // { text: '门素材', link: 'https://www.17sucai.com/user/800544' },
    { text: '掘金', link: 'https://juejin.cn/user/4054654613988718' },
    { text: '思否', link: 'https://segmentfault.com/u/xishui_5ac9a340a5484' },
    { text: '知乎', link: 'https://www.zhihu.com/people/eveningwater' },
    { text: 'stackoverflow', link: 'https://stackoverflow.com/users/10505577/eveningwater' },
    { text: '我的博客', link: 'https://www.cnblogs.com/eveningwater/' },
    // { text: '我的博客', link: 'https://eveningwater.github.io/#/' },
    // { text: 'code-segment', link: 'https://eveningwater.github.io/code-segment/#/' },
    // { text: 'github', link: 'https://github.com/eveningwater/my-web-projects' },
    { text: '码云', link: 'https://gitee.com/eveningwater' },
]