module.exports = [
    { text: 'home', link: '/' },
    // { text: 'my website', link: 'https://www.eveningwater.com' },
    // { text: 'ewColorPicker', link: 'https://eveningwater.github.io/ew-color-picker/' },
    // { text: '17sucai', link: 'https://www.17sucai.com/user/800544' },
    { text: 'juejin', link: 'https://juejin.cn/user/4054654613988718' },
    { text: 'segmentfault', link: 'https://segmentfault.com/u/xishui_5ac9a340a5484' },
    { text: 'zhihu', link: 'https://www.zhihu.com/people/eveningwater' },
    { text: 'stackoverflow', link: 'https://stackoverflow.com/users/10505577/eveningwater' },
    { text: 'my blog', link: 'https://www.cnblogs.com/eveningwater/' },
    // { text: 'my blog', link: 'https://eveningwater.github.io/#/' },
    // { text: 'code-segment', link: 'https://eveningwater.github.io/code-segment/#/' },
    // { text: 'github', link: 'https://github.com/eveningwater/my-web-projects' },
    { text: 'gitee', link: 'https://gitee.com/eveningwater' },
]